#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Install the lightweight Open Ralph -> OMX integration.

Usage:
  contrib/omx/install.sh [--dry-run] [--force-config] [--symlink]

Options:
  --dry-run        Print actions without writing files.
  --force-config   Replace an existing agents.json after saving a timestamped backup.
  --symlink        Symlink wrappers instead of copying them.
  -h, --help       Show this help.

Environment overrides:
  RALPH_OMX_BIN_DIR      default: $HOME/.local/bin
  RALPH_OMX_CONFIG_DIR   default: $HOME/.config/open-ralph-wiggum
  RALPH_OPEN_BIN          default: this checkout's bin/ralph.js
USAGE
}

dry_run=0
force_config=0
link_mode=copy
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) dry_run=1 ;;
    --force-config) force_config=1 ;;
    --symlink) link_mode=symlink ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[install-ralph-omx] unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

resolve_self() {
  local source="$1"
  while [ -L "$source" ]; do
    local dir
    dir="$(cd -P "$(dirname "$source")" >/dev/null 2>&1 && pwd)"
    source="$(readlink "$source")"
    [[ "$source" != /* ]] && source="$dir/$source"
  done
  cd -P "$(dirname "$source")" >/dev/null 2>&1 && pwd
}

SCRIPT_DIR="$(resolve_self "${BASH_SOURCE[0]}")"
BIN_DIR="${RALPH_OMX_BIN_DIR:-$HOME/.local/bin}"
CONFIG_DIR="${RALPH_OMX_CONFIG_DIR:-$HOME/.config/open-ralph-wiggum}"
CONFIG_FILE="$CONFIG_DIR/agents.json"
ENV_FILE="$CONFIG_DIR/omx.env"
RALPH_BIN_SOURCE="${RALPH_OPEN_BIN:-$(cd "$SCRIPT_DIR/../.." >/dev/null 2>&1 && pwd)/bin/ralph.js}"

run() {
  printf '[install-ralph-omx] %s\n' "$*"
  if [[ "$dry_run" -eq 0 ]]; then
    "$@"
  fi
}

install_wrapper() {
  local name="$1"
  local src="$SCRIPT_DIR/$name"
  local dst="$BIN_DIR/$name"
  if [[ "$link_mode" == "symlink" ]]; then
    run ln -sfn "$src" "$dst"
  else
    run cp "$src" "$dst"
    run chmod +x "$dst"
  fi
}

run mkdir -p "$BIN_DIR" "$CONFIG_DIR"
install_wrapper ralph-omx
install_wrapper omx-codex-exec-for-ralph

if [[ -e "$ENV_FILE" && "$dry_run" -eq 0 ]]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi
printf '[install-ralph-omx] write %s with RALPH_OPEN_BIN=%s\n' "$ENV_FILE" "$RALPH_BIN_SOURCE"
if [[ "$dry_run" -eq 0 ]]; then
  cat > "$ENV_FILE" <<EOF_ENV
# Generated by contrib/omx/install.sh. Edit if the Open Ralph checkout moves.
RALPH_OPEN_BIN='$RALPH_BIN_SOURCE'
EOF_ENV
fi

if [[ -e "$CONFIG_FILE" && "$force_config" -eq 0 ]]; then
  printf '[install-ralph-omx] keep existing %s (use --force-config to replace)\n' "$CONFIG_FILE"
else
  if [[ -e "$CONFIG_FILE" && "$dry_run" -eq 0 ]]; then
    backup="$CONFIG_FILE.bak.$(date +%Y%m%d%H%M%S)"
    printf '[install-ralph-omx] backup %s -> %s\n' "$CONFIG_FILE" "$backup"
    cp "$CONFIG_FILE" "$backup"
  fi
  printf '[install-ralph-omx] write %s with adapter command %s\n' "$CONFIG_FILE" "$BIN_DIR/omx-codex-exec-for-ralph"
  if [[ "$dry_run" -eq 0 ]]; then
    CONFIG_FILE="$CONFIG_FILE" ADAPTER_COMMAND="$BIN_DIR/omx-codex-exec-for-ralph" python3 - <<'PY_JSON'
import json, os
config = {
    "version": "1.0",
    "agents": [
        {
            "type": "codex",
            "command": os.environ["ADAPTER_COMMAND"],
            "configName": "OMX Codex Exec",
            "argsTemplate": "codex",
            "envTemplate": "default",
            "parsePattern": "codex",
        }
    ],
}
with open(os.environ["CONFIG_FILE"], "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2)
    f.write("\n")
PY_JSON
  fi
fi

cat <<EOF2
[install-ralph-omx] done
  wrappers: $BIN_DIR/ralph-omx, $BIN_DIR/omx-codex-exec-for-ralph
  config:   $CONFIG_FILE
  env:      $ENV_FILE
  smoke:    RALPH_OMX_SHIM_DEBUG=1 ralph-omx --help | head -80
EOF2
